### ISSUE TITLE
Check/Review unused code

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-signing-tools#147]
- [x] **Caching**: `cache_get_nonce`, `cache_put_nonce`, `cache_len` and `get_balance`
- [ ] **WASM**: `address_to_object` and `signature_to_object`

**Comment by rllola** [comment]
`address_to_object` and `signature_to_object` are both used and doesn't seem to have any TODO left and obvious warning. Maybe this can closed ?

**Comment by jleni** [comment]
let's close it for now
