### ISSUE TITLE
cbor pure js implementation won't throw an error for extra bytes

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#172]
See https://github.com/dignifiedquire/borc/issues/47

**Comment by rllola** [comment]
It has been mentioned in the issue that we should change for this library for CBOR instead : https://github.com/ipld/js-ipld-dag-cbor

It should raise the error when detecting extra bytes.

**Comment by rllola** [comment]
The lib has been modified but the latest release still don't include this specific fix. Let's wait for version v0.15.4 and block the version before closing this issue.

**Comment by jleni** [comment]
@rllola is this still relevant?

**Comment by rllola** [comment]
Yes, it is still relevant. They haven't done the release with patch. I have created an issue asking if they could do a release with this commit as it has been a month.
