### ISSUE TITLE
Swift call problem

### ISSUE THREAD

**Issue by wjd-jax** [Zondax/filecoin-signing-tools#197]
The filecoin_signer_ffi.h file does not provide a declaration of signature, but only a method to generate a private key, which can't be called properly after swift compilation

**Comment by jleni** [comment]
Yes, we only provide an example of how to use FFI. You need to expose the methods you need using the example as guidance.

**Comment by wjd-jax** [comment]
Thanks for your reply, we have successfully generated .a file, but our team does not have Rust developers and are not familiar with FFI generation. Could you provide a signature method header file

**Comment by v-sharaev** [comment]
@wjd-jax hi, can you help me with header file?
