### ISSUE TITLE
serializeParams is not a function

### ISSUE THREAD

**Issue by gfpacheco** [Zondax/filecoin-signing-tools#200]
Hi, I'm building a Lotus client but I can't get the params cbor encoding right.

Initially, I thought I could send the entire message to be signed: `{ ..., params: { code_cid: ... } }`, but then your library complains that params should be a string instead.

Then I tried to use the `serializeParams` function as it's in the documentation, but there's no such function on your exports.

Then I tried to serialize the params by myself before signing, but the signing library expects a hex encoded string while Lotus expects a base64 encoded string.

I fixed it, but my message isn't accepted on the chain because `BlockHeader: cbor input had wrong number of fields`.

This is how I'm building my request:

```javascript
import dagCBOR from 'ipld-dag-cbor';
import { Buffer } from 'multihashing-async';
import * as wasm from '@zondax/filecoin-signer-wasm';

const privateKey = '...';

const params: {
  CodeCID: '...',
  ConstructorParams: {
    // ...
  },
};

const serializedParams = dagCBOR.util.serialize({
  CodeCID: params.CodeCID,
  ConstructorParams: dagCBOR.util.serialize(params.ConstructorParams).toString('hex'),
}).toString('hex');

const message = {
  // ...
  params: serializedParams,
};

const signedMessage = JSON.parse(wasm.transactionSignLotus(message, privateKey))

signedMessage.Message.Params = Buffer.from(signedMessage.Message.Params, 'hex').toString(
  'base64',
);

// send signedMessage to Lotus
```

Should the `serializeParams` be exported? If not, am I serializing the params correctly?

**Comment by rllola** [comment]
Hi @gfpacheco 

I think one of the reason it is not working it is because the name has been changed to `@zondax/filecoin-signer`. And it is in the latest that the `serializeParams` function has been added.

Might also be why your `params` doesn't work as precedent version of the lib only supported simple transaction (method 0).

**Comment by rllola** [comment]
My bad the name in npm is `@zondax/filecoin-signing-tools`

**Comment by gfpacheco** [comment]
Oh no! The name changed and I didn't notice.

But anyway, now that the function is available I'm getting this error: `Error parsing parameters: data did not match any variant of untagged enum MessageParams`.

I'm trying to recreate [this message](https://github.com/filecoin-project/lotus/blob/master/paychmgr/simple.go#L20) and I need my params to be like this:

```javascript
code_cid: "...",
constructor_params: {
  from: "...",
  to: "...",
},
```

Do you really need to enforce types on the constructor_params? I feel like it would be much easier if you could accept anything inside the params (or just inside constructor_params).

**Comment by rllola** [comment]
So we only support multisig message creation. And yes it is written in rust and using external rust dependencies so we enforce it.

But you should be able to use the `transactionSignLotus` now and giving the hex string of the serialize parameters in `params`. Like you tried before. The latest version should support it.

**Comment by gfpacheco** [comment]
Right, the signing does work, you can close this issue.

But I would be grateful if you could tell me if there's anything wrong with my function:

```javascript
function serializeParams({ CodeCID, ConstructorParams }) {
  return dagCBOR.util.serialize({
    CodeCID,
    ConstructorParams: dagCBOR.util.serialize(ConstructorParams).toString('base64'),
  }).toString('base64');
}
```

I keep getting `BlockHeader: cbor input had wrong number of fields` even if the signing works.

**Comment by rllola** [comment]
I am not sure but it could be that it need to be an "hex" string and not "base64"....

Try this :
```
function serializeParams({ CodeCID, ConstructorParams }) {
  return dagCBOR.util.serialize({
    CodeCID,
    ConstructorParams: dagCBOR.util.serialize(ConstructorParams).toString('hex'),
  }).toString('hex');
}
```

**Comment by gfpacheco** [comment]
Actually, my params are being replaced by `""` on the signed message.

```javascript
const message = {
  // ...
  params: "...",
};

const signedMessage = signer.transactionSignLotus(message, privateKey);
// signedMessage.params === ""
```

**Comment by rllola** [comment]
Ok yeah that's not good... I will take a look at it.

I believe unfortunately the latest commit for this hasn't made it to `master`. Because I can see the code in `dev` for this...

**Comment by gfpacheco** [comment]
Hi @rllola, did you have time to look at this?

**Comment by rllola** [comment]
@gfpacheco Yes so it is indeed only in `dev`. We are also adding an update for `ledger-rs` unfortunately there is a small bug that we are hunting. As soon as it is solved we are releasing a new version.

**Comment by rllola** [comment]
Hey @gfpacheco !
New release is out https://www.npmjs.com/package/@zondax/filecoin-signing-tools
I hope it solve your problem.
