### ISSUE TITLE
Actor address expected length of 32 instead of 20

### ISSUE THREAD

**Issue by gfpacheco** [Zondax/filecoin-signing-tools#243]
https://github.com/Zondax/filecoin-signing-tools/blob/29999eb6af5b133ce468b2b7b2804b23bebf67c6/signer-npm/js/src/utils.js#L113-L116

As opposed to the official lib:

https://github.com/filecoin-project/go-address/blob/6ca104a432f9e6b3353c183773d5645f574a3118/address.go#L319-L323

**Comment by rllola** [comment]
We already had someone also made a PR about this. The lib was build using the spec given by filecoin : https://filecoin-project.github.io/specs/#protocol-2-actor

It mentioned the payload being the result of sha256 which is 32 bytes if I not mistaken. But indeed the official lib seems to expect 20 bytes length.

I am going to dig on this one. It is possible the specs are out of date...

**Comment by rllola** [comment]
So in rust it is also 20 and they actually don't use sha256 like in the spec but blake2b-160 (https://chainsafe.github.io/forest/src/forest_address/lib.rs.html#302)

We can see here it here being used https://chainsafe.github.io/forest/src/forest_address/lib.rs.html#96

**Comment by jleni** [comment]
Thanks for the info! 
I am worried that the specs we were using and the implementations are not matching.

I have just opened an issue about this, so the specs team can update things
