### ISSUE TITLE
wasm.transactionSignRawWithDevice() returns a 64 byte signature, instead of a 65 byte one

### ISSUE THREAD

**Issue by popra** [Zondax/filecoin-signing-tools#255]
Hello,

`wasm.transactionSignRawWithDevice()` in 0.6.3 returns a 64 byte signature, while lotus expects a 65 byte signature. The signature returned by `wasm.transactionSignRawWithDevice()` is missing the recovery id. While the recovery id can be added after the signature generation (lotus doesn't actually seem to use) it could be a good idea to have it returned by `wasm.transactionSignRawWithDevice()` for future proofing

**Comment by jleni** [comment]
This is addressed in PR #284 , however, we are aware of a problem related to issue https://github.com/Zondax/filecoin-signing-tools/issues/205

As explained, at the moment, we would recommend using the pure js alternative when dealing with Ledger devices:

https://github.com/Zondax/ledger-filecoin-js
https://www.npmjs.com/package/@zondax/ledger-filecoin
