### ISSUE TITLE
Javascript cbor lib doesn't detect extra bytes anymore

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#267]
The javascript cbor lib doesn't throw an error when extra bytes are append to the message.
See tests : 
- `should fail to parse because of extra bytes`
- `should fail to parse because of extra bytes (non null)`

**Comment by xiaomingloveqinger** [comment]
same here

**Comment by xiaomingloveqinger** [comment]
is filecoin_signer_wasm_bg.wasm not been updated ?

**Comment by rllola** [comment]
> is filecoin_signer_wasm_bg.wasm not been updated ?

This file is generated, so it should be.

Do you use the pure javascript lib or the wasm ?

**Comment by xiaomingloveqinger** [comment]
> > is filecoin_signer_wasm_bg.wasm not been updated ?
> 
> This file is generated, so it should be.
> 
> Do you use the pure javascript lib or the wasm ?

i am using the wasm

**Comment by rllola** [comment]
@xiaomingloveqinger Could you copy/paste the string you are trying to parse ? You might have encounter another issue than the one this ticket has been open for.

**Comment by jleni** [comment]
@xiaomingloveqinger any updates?

**Comment by jleni** [comment]
I will close it for now.. 
@xiaomingloveqinger please reopen if this is still an issue
