### ISSUE TITLE
Find a BLS javascript library for test and pure js lib

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#269]
We need to support BLS signing. We need to pick a proper javascript lib that we could use in the pure js lib and for tests.

:link: [zboto Link](https://app.clickup.com/t/2r5b6c8)

**Comment by new9527** [comment]
how to create t3 address and sign transaction to t3 address with javascript lib?

**Comment by jtomtan** [comment]
> We need to support BLS signing. We need to pick a proper javascript lib that we could use in the pure js lib and for tests.

We need the same thing. Have you guys found the solution?

**Comment by jleni** [comment]
No, for the moment, we recommend using the WASM-based implmentation.

**Comment by jtomtan** [comment]
> No, for the moment, we recommend using the WASM-based implmentation.

Yes. We are also trying the wasm based solution. Trying to build the wasm js from the source code. But not sure if we can succeed. Can we share the solutions if you are going to it the same way? You can reach me at telegram: https://t.me/ownbit

**Comment by rllola** [comment]
It looks like ChainSafe has been working on a BLS javascript lib.
https://github.com/ChainSafe/bls

It might be a good fit.

**Comment by jleni** [comment]
Let's use it and run comparison tests with the WASM version

**Comment by rllola** [comment]
Looks like @ChainSafe/bls is ESM only so we can't use `require` to load the library. One way would be to convert the whole lib to be ESM only but it would break a lof of things for downstream devs. The other way is just to make the `transactionSign` async.

**Comment by rllola** [comment]
Now that we have migrated to ES module we can implement BLS signature for the pure js lib.

**Comment by hunjixin** [comment]
i see wasm implement in current version, but why have a todo for signTransaction

```
 // TODO: support BLS scheme
  const signedMessage: SignedMessage = {
    Signature: {
      Data: signature.toString('base64'),
      Type: ProtocolIndicator.SECP256K1,
    },
  }
```
any work need to do, is this signature correctly

**Comment by emmanuelm41** [comment]
Refers to this issue on the new package 
https://github.com/Zondax/izari-filecoin/issues/71
