### ISSUE TITLE
Payment channel : "time_lock_min" and "time_lock_max" not supported yet

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#271]
Seems like `time_lock_min` and `time_lock_max` are not supported yet. Probably fix the value to 0 and update for when it is supported.

**Comment by rllola** [comment]
I am not sure we still want to do this. Maybe it should be closed.

**Comment by jleni** [comment]
Let's close for now. We can get a request later if Glif or someone needs this.
