### ISSUE TITLE
Support for mnemonics in other languages

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#287]
The Glif Wallet received a request to support mnemonics in other languages, what would it take to make this happen on the wasm side of things? 

Relevant issue in the wallet repo: https://github.com/openworklabs/filecoin-web-wallet/issues/491

**Comment by rllola** [comment]
I have looked into the bip39 lib I am using in rust for this. Unfortunately it only support english for now (https://docs.rs/bip39/0.5.1/src/bip39/language.rs.html#46-48)

I could do a PR first to add other language to this specific lib.

**Comment by rllola** [comment]
I looked into the wrong lib. The lib we are currently using support different languages... sorry

https://docs.rs/tiny-bip39/0.8.0/bip39/enum.Language.html
