### ISSUE TITLE
Important: same seed phrase generates different looking filecoin addresses

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#295]
`t` addresses and `f` addresses are meant to be interoperable for mainnet launch. According to Aayush from Filecoin team, the same private key or seed phrase should generate _identical_ addresses, with the network protocol prefix being the exception (`t` or `f`). For example:

private key: `12345` should be able to generate `f1abcde` AND `t1abcde` - this is what's happening in Lotus right now, depending on a build param that tells Lotus to use `f` or `t` with the address when it gets serialized into a string. 

Right now, my same private key generates two completely different looking addresses, not _just_ the network protocol prefix at the beginning.

**Comment by jleni** [comment]
This is not correct. The mnemonic uses a derivation path and the private key is derived using BIP44 (following that for both mainnet and testnet). The paths for testnet and mainnet are different and the same will happen in Ledger devices.

**Comment by jleni** [comment]
What aayush described is how you go from a pubkey to an address, where it is true that lotus does not make a difference. But following BIP44 does. It is likely that other wallets such as metamask or trustwallet may result in a similar problem.
BIP44 defines that testnet address a derived using a path starting with 44'/1'/... while mainnet address require registering the coin value

**Comment by Schwartz10** [comment]
Sorry, I made a small mistake in my first message - Aayush said the same _private key_ should produce the identical addresses (network prefix exception). He didn't say the seed phrase part, which is where I was definitely confused.

So this may actually not be that big of an issue then... I can't imagine miners or anyone who would be using a `t` address did so with a seed phrase...?

And the glif wallet should then be acting appropriately when a user inputs a seed phrase.. I will check this and confirm

**Comment by jleni** [comment]
@Schwartz10 should I close this issue?
