### ISSUE TITLE
Voucher signature verification

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-signing-tools#300]
As voucher signatures behave in a slightly different way, we need another function to verify signed vouchers

@mgoelzer

**Comment by rllola** [comment]
The voucher doesn't have the signer address info that we can match the recovered address with. In order to verify the voucher signature you need to provide the signature and the public key/address.

It needs a new function that will look like this `verify_voucher_signature(voucher, signature, public_key)`. And there is 2 cases the pubkey could be either SECP or BLS.

**Comment by rllola** [comment]
Or even better : `verify_voucher_signature(signedVoucherBase64, public_key)`

**Comment by mgoelzer** [comment]
> verify_voucher_signature(voucher, signature, public_key)

I think this version might be simpler to use, since the caller doesn't have to do that cbor.deserialize(...) stuff, and the method signature doesn't change for SECP vs BLS keys.

**Comment by rllola** [comment]
> > verify_voucher_signature(voucher, signature, public_key)
> 
> I think this version might be simpler to use, since the caller doesn't have to do that cbor.deserialize(...) stuff, and the method signature doesn't change for SECP vs BLS keys.

So I went for `verify_voucher_signature(signedVoucherBase64, address_signer)`. The advantage for this is that you don't need to deserialize the base64 voucher string to get the signature and the `address_signer` give the me the information I need about the type of signature I should check.

I should be done today. I will also update the example to illustrate how it can be used.

**Comment by mgoelzer** [comment]
Thanks @rllola.  I was misunderstanding `signedVoucherBase64` to mean the [10] element of the array after deserialization (the way we had it in one of the test programs).  

When you say signedVoucherBase64 you just mean do a `let signedVoucher = filecoin_signer.signVoucher(voucher, privateKeyBase64` and then convert `signedVoucher` value to base64, right?
