### ISSUE TITLE
Need to expose gas parameters in updatePymtChan, settlePymtChan and collectPymtChan

### ISSUE THREAD

**Issue by mgoelzer** [Zondax/filecoin-signing-tools#302]
PR #298 exposed the 3 gas parameters to Javascript in `createPymtChan`.  However, there are 3 additional functions where we need to expose gas to the user in the same way:

 - [ ] updatePymtChan
 - [ ] settlePymtChan
 - [ ] collectPymtChan

**Comment by jleni** [comment]
No problem, I will do this ASAP
