### ISSUE TITLE
Need to use gas estimator

### ISSUE THREAD

**Issue by mgoelzer** [Zondax/filecoin-signing-tools#303]
If we first generate unsigned messages with all gas values set to 0, like this:

```
  Message: {
    From: 't1a25ihzpz7jb6wgjkkd7cndnhgo4zbbap6jc5pta',
    GasFeeCap: '0',
    GasLimit: 0,
    GasPremium: '0',
    Method: 2,
    Nonce: 23,
    Params: 'g4tDAPIHAABA9gAWQgD6AIBYQgFcAGnWDRd8G2OmYqJHLQLp2ul0tsAz//nx1PJtNUmg1yJE3h5xmHx95NtnaJsV9uyJv7Y8RgUx7i7Z3W/gUT6qAUBA',
    To: 't01010',
    Value: '0'
  }
```

Then we can pass that message in as the second argument to `GasEstimateMessageGas()` API call.  What we will get back is the same message with the 3 gas fields filled in.

The full signature is:
`GasEstimateMessageGas(context.Context, *types.Message, *MessageSendSpec, types.TipSetKey) (*types.Message, error)`
Here's what to do with each paraneter:
 - context:   null
 - *types.Message:  the message structure as demonstrated above (all gas fields = 0)
 - *MessageSendSpec:  null
 - types.TipSetKey:  ""

At the Javascript level, user should call `filecoin_signer.createPymtChan(..., 0, 0, 0)` to indicate he wants real time gas estimation as described in this issue.  But if he calls it like `filecoin_signer.createPymtChan(..., 300, 1000000, 25000000)` then use the user-specified values.  This would mean that gas estimation has to be done in the Rust code, but it would make the library way more usable.

[This Slack discussion with Kuba](https://filecoinproject.slack.com/archives/CP50PPW2X/p1601641609138100) clarified a lot of this stuff for me.

**Comment by jleni** [comment]
related to #272

**Comment by jleni** [comment]
I will close the other issue to avoid duplication.

**Comment by jleni** [comment]
Doing gas estimation in WASM is not ideal because it would require adding a fair amount of additional configuration/information such endpoint information, JWT tokens, etc.
I think the best option is that we still use axios and this function that "overrides" the values is written as an example in JS that can be later used. 
Basically, a simple wrapper that makes the axios call and replaces the values as you described.

**Comment by mgoelzer** [comment]
That sounds fine.

Sorry FC's been having so much gas fluctuation lately!  Unfortunately, I expect this to happen periodically, so I think we need code using this library to be resilient against gas cost surges.  Wrapper in JS sounds fine to me.

**Comment by mgoelzer** [comment]
@rllola As part of this, can you update `examples/wasm_node/payment_channel.js` so I have an example to copy of how to use gas estimation?
