### ISSUE TITLE
ProtocolNotSupported("BLS")

### ISSUE THREAD

**Issue by Wangmmx** [Zondax/filecoin-signing-tools#312]
When I use the secp256k1 format address to transfer funds to the bls format address, an error will be reported：ProtocolNotSupported("BLS")
Does the current nodejs npm library not support BLS format signatures?

If it is not supported, what should I do for offline signing?looking forward to your reply!

**Comment by jleni** [comment]
BLS is not supported in the pure JS library. You need to use the WASM version if you need BLS.

Related issue #269

**Comment by jleni** [comment]
closing as duplicate

**Comment by Wangmmx** [comment]
![image](https://user-images.githubusercontent.com/22836587/95577518-df0b5000-0a64-11eb-9c3d-5acbe5f17fe9.png)
I found that this place is restricted. There was a version with this logic before, can I continue to use this
