### ISSUE TITLE
Broken links to examples

### ISSUE THREAD

**Issue by hsanjuan** [Zondax/filecoin-signing-tools#313]
We are sending people to https://zondax.ch/projects/filecoin-signing-tools/#ffi-examples but all the links to examples are broken.

**Comment by rllola** [comment]
Yes you are right. It should redirect to github code.

**Comment by jleni** [comment]
We will soon publish a completely new website. For the moment, the best option is to look at the examples in this repository.

**Comment by hsanjuan** [comment]
I know that examples are in the repo.

What I am telling you is that the users that land on your current website referred from the official filecoin docs do not know it, and the website has no clear links to the repo, but the repo has prominent links to the website (first line in README). So one minute spent fixing those links would be well invested imho regardless of your future plans to do things.

Anyways, I just wanted to make sure the issue was known.

**Comment by jleni** [comment]
Yes! Let's keep this open so we don't lose track of this! we need to improve this
