### ISSUE TITLE
When serializing, why do some fields need to add 0x00 in front?

### ISSUE THREAD

**Issue by vae520283995** [Zondax/filecoin-signing-tools#314]
/* signed message :
82                                      # array(2)
   8A                                   # array(10)
      00                                # unsigned(0)
      55                                # bytes(21)
         01FD1D0F4DFCD7E99AFCB99A8326B7DC459D32C628 # "\x01\xFD\x1D\x0FM\xFC\xD7\xE9\x9A\xFC\xB9\x9A\x83&\xB7\xDCE\x9D2\xC6("
      55                                # bytes(21)
         011EAF1C8A4BBFEEB0870B1745B1F57503470B7116 # "\x01\x1E\xAF\x1C\x8AK\xBF\xEE\xB0\x87\v\x17E\xB1\xF5u\x03G\vq\x16"
      01                                # unsigned(1)
      44                                # bytes(4)
         000186A0                       # "\x00\x01\x86\xA0"
      19 09C4                           # unsigned(2500)
      42                                # bytes(2)
         0001                           # "\x00\x01"
      42                                # bytes(2)
         0001                           # "\x00\x01"
      00                                # unsigned(0)
      40                                # bytes(0)
                                        # ""
   58 42                                # bytes(66)
      0106398485060CA2A4DEB97027F518F45569360C3873A4303926FA6909A7299D4C55883463120836358FF3396882EE0DC2CF15961BD495CDFB3DE1EE2E8BD3768E01 # "\x01\x069\x84\x85\x06\f\xA2\xA4\xDE\xB9p'\xF5\x18\xF4Ui6\f8s\xA409&\xFAi\t\xA7)\x9DLU\x884c\x12\b65\x8F\xF39h\x82\xEE\r\xC2\xCF\x15\x96\e\xD4\x95\xCD\xFB=\xE1\xEE.\x8B\xD3v\x8E\x01"
*/

value 000186A0
gasefeecap 0001
gaspremium 0001

Why they need to add 0x00

**Comment by jleni** [comment]
This is the way Filecoin/Lotus serializes BigInts

https://github.com/filecoin-project/go-state-types/blob/41ea465f274f149649ca2e8e2f1ab079cbe7a4c0/big/int.go#L221-L234
