### ISSUE TITLE
How to connect ledger nano x

### ISSUE THREAD

**Issue by vae520283995** [Zondax/filecoin-signing-tools#325]
How to connect ledger nano x

**Comment by rllola** [comment]
Sorry but we would need more information on what you are trying to do. Please let us know if you have still trouble with this.

**Comment by vae520283995** [comment]
Does only Lotus support ledger nano x? Are there other wallets? Too much trouble building nodes

**Comment by jleni** [comment]
No, Glif is a Filecoin webwallet that has Ledger support https://wallet.glif.io/
