### ISSUE TITLE
createMultisig needs v2 actor support

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#327]
When trying to create a new multisig actor from the `wasm.createMultisig` I get the following error:

```
message execution failed: exit 18, reason: caller type bafkqadlgnfwc6mrpmfrwg33vnz2a cannot exec actor type bafkqadtgnfwc6mjpnv2wy5djonuwo (RetCode=18)
```

Sample tx:
```
from: "f1nq5k2mps5umtebdovlyo7y6a3ywc7u4tobtuo3a"
gasfeecap: "0"
gaslimit: 0
gaspremium: "0"
method: 2
nonce: 0
params: "gtgqUwABVQAOZmlsLzEvbXVsdGlzaWdYGoOBVQFsOq0x8u0ZMgRuqvDv48DeLC/TkwEB"
to: "t01"
value: "1000000000000000000"
```

The params field is (presumably) wrong, since the correct actor type should be bafkqadtgnfwc6mrpnv2wy5djonuwo

My guess would be what we have (`bafkqadtgnfwc6mjpnv2wy5djonuwo`) is the v1 multisig actor CID, but you should be using the v2 CID `bafkqadtgnfwc6mrpnv2wy5djonuwo`

**Comment by rllola** [comment]
Indeed we are still using V1, should be not too difficult to fix. Do you know if lotus still support V1 ? If they don't I won't need to support both and makes it even easier.

**Comment by jleni** [comment]
We had a similar discussion about payment channels v1 here:

https://github.com/Zondax/filecoin-signing-tools/pull/317#issuecomment-713304140

If you can get a confirmation, maybe we just deprecated v1 and move directly to v2

**Comment by Schwartz10** [comment]
@rllola @jleni according to Kubuxu, we only allow creation of v2 multisigs. Can deprecate V1 multisig is my guess

**Comment by jleni** [comment]
mmm.. just to clarify (we are talking in Slack but I was already writing this here)

We may be able to deprecate `creation` of v1... but how about all the other operations?
Did all `v1` multisign got migrated to `v2`.. 

so I would invert the question here:
- where do you need support for v1?
- what happens if we remove v1 support completely?

**Comment by Schwartz10** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/12353734/98951020-b80ec680-24c7-11eb-8ce8-6687111e93bd.png">

**Comment by Schwartz10** [comment]
For determining methods that have changed -- from Kubuxu:

```
If you see something like type ProposeParams = multisig0.ProposeParams it means that params were the same in v0 (we skipped v1 really).
```

Constructor params have changed https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L76-L83

**Comment by rllola** [comment]
Looks like there is a new method added too. Do we need to support `LockBalance` ? I can do two PRs to have a first release faster.

**Comment by Schwartz10** [comment]
Eventually `LockBalance` might need to be supported, but for now, just construction
