### ISSUE TITLE
Add support for Multisig v2 `LockBalance`

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-signing-tools#329]
Eventually `LockBalance` might need to be supported, but for now, just construction

_Originally posted by @Schwartz10 in https://github.com/Zondax/filecoin-signing-tools/issues/327#issuecomment-726230634_

**Comment by Schwartz10** [comment]
Gah @jleni - just learned - we'll need to add support for LockBalance too. PL wants to be able to fund multisig wallets _after_ their construction according to a vesting schedule, too.
