### ISSUE TITLE
deserializeConstructorParams should work for multisigs

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#333]
I'd expect something like this to work: 

```js
const tx = wasm.createMultisig(
      wallet.address,
      [...signerAddresses],
      '100',
      1,
      0,
      '0',
      '0'
    )

wasm.deserializeConstructorParams(tx.params, 'fil/2/multisig')
```

Instead, 

```
"Error deserializing constructor parameters: Cannot deserilaize parameters | Serialization error for Cbor protocol: invalid type: newtype struct, expected a sequence" 
```

**Comment by rllola** [comment]
The error seems to come from `forest_encoding`. I am trying to find how to fix this...

**Comment by rllola** [comment]
Nope, I have found the problem. I am actually expecting the `constructor_params` value as a base64 string and not the `params`. Meaning your `params` is the this struct : 
```
pub struct ExecParams {
    pub code_cid: Cid,
    pub constructor_params: Serialized,
}
```
and the function is expecting the second parameter called `constructor_params` which is a base64 string.

**Comment by Schwartz10** [comment]
Sorry @rllola not sure I'm understanding. Could you just paste a little example code snippet in here?

**Comment by rllola** [comment]
For example @Schwartz10 you have a constructor parameter for multisig that looks like this : 
```
    "params": {
      "from": "t17uoq6tp427uzv7fztkbsnn64iwotfrristwpryy",
      "to": "t1d2xrzcslx7xlbbylc5c3d5lvandqw4iwl6epxba"
    }
```
Once serialized you have the base64 string: `glUB/R0PTfzX6Zr8uZqDJrfcRZ0yxihVAR6vHIpLv+6whwsXRbH1dQNHC3EW`

you can deserialize that.

**Comment by Schwartz10** [comment]
@rllola sorry I'm confused - aren't the multisig constructor parameters:

```
type ConstructorParams struct {
	Signers               []addr.Address
	NumApprovalsThreshold uint64
	UnlockDuration        abi.ChainEpoch
	StartEpoch            abi.ChainEpoch
}
```

see [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/multisig_actor.go#L78-L83)

Basically, I'd just like to be able to take the `EXEC` call, and understand what was passed for `Signers` `NumApprovalsThreshold` `UnlockDuration` and `StartEpoch`. For example, I'd like to be able to take this transaction https://filfox.info/en/message/bafy2bzacecsmntgtfoddrnxd5i3fowpgk2dpkpmvvavp2stujk45rhp3ef4cy and decode its parameters as listed above ^^

**Comment by rllola** [comment]
Yeah sorry I gave you the payment channel constructor as an example.

For now you can't do that directly. You will need to deserialize params and then take the constructor params base64 string returned and pass it to `deserializeConstructorParams`.

**Comment by Schwartz10** [comment]
@rllola when I try to deserialize the params I get:

```
Error deserializing parameters: Cannot deserilaize parameters | Serialization error for Cbor protocol: invalid type: newtype struct, expected a borrowed byte array
```

Sorry I'm so confused, but can you show me a test or code snippet that takes `gtgqUwABVQAOZmlsLzIvbXVsdGlzaWdYIISBVQFsOq0x8u0ZMgRuqvDv48DeLC/TkwEYZBoAA9qL` and deserializes it into 
```
type ConstructorParams struct {
	Signers               []addr.Address
	NumApprovalsThreshold uint64
	UnlockDuration        abi.ChainEpoch
	StartEpoch            abi.ChainEpoch
}
```

I understand this may be two calls (which is fine), but I can't seem to string them together to get it to work

**Comment by rllola** [comment]
Hey @Schwartz10 

Here a code snippet (untested): 
```
const params = "gtgqUwABVQAOZmlsLzIvbXVsdGlzaWdYIISBVQFsOq0x8u0ZMgRuqvDv48DeLC/TkwEYZBoAA9qL"
const exec_params = filecoin_signer.deserializeParams(params, "fil/1/init", 2)
console.log(exec_params)
/* Result should look like this
{
      "code_cid": "bafkqadtgnfwc6mrpnv2wy5djonuwo",
      "constructor_params": "hIFVAWw6rTHy7RkyBG6q8O/jwN4sL9OTARhkGgAD2os="
    }
*/
const constructor_params = filecoin_signer.deserializeConstructorParams(exec_params.constructor_params, "fil/2/multisig")
console.log(constructor_params)
```
Let me know if it works for you. Sorry if precedents messages were confusing.

**Comment by jleni** [comment]
@Schwartz10 @rllola is this still pending or can be closed?

**Comment by rllola** [comment]
I have added a test to demonstrate it works. I am closing this then.
