### ISSUE TITLE
Browser usage is broken due to how wasm is loaded

### ISSUE THREAD

**Issue by ukstv** [Zondax/filecoin-signing-tools#343]
Currently the package uses naive `import * as wasm from '...some_file.wasm'` import of wasm artefact. This works with Node.js but fails miserably within Next.js or CRA. It is necessary to load wasm binary asynchronously, otherwise out of the box bundlers fail. While I understand, this is a problem of bundlers, it would be good if Zondax team could provide some ad-hoc async loading of WASM artefact, like [Polkadot] does.

**Comment by rllola** [comment]
Do you mean that importing it like in the [bootstrap.js file](https://github.com/Zondax/filecoin-signing-tools/blob/master/examples/wasm_browser/bootstrap.js) doesn't work for you ?

**Comment by ukstv** [comment]
It does in principle. Really, with bundlers and TS compilers async import turns effectively into require. So, as a suggestion, could you support vanilla `require` with some async loader for wasm?
