### ISSUE TITLE
getCid is not working for BLS

### ISSUE THREAD

**Issue by APshenkin** [Zondax/filecoin-signing-tools#350]
```javascript
const fil = require('@zondax/filecoin-signing-tools');

const signed = {
  "message": {
    "to": "t1kj2fedndezlcawu4nxr6pqisiwz2asgonsy3tny",
    "from": "t3ryp7nacthkhye7dpfzx3fv3btmj5xnegc5v4yqojsaxnhld4jxdqvrsg22qjsuuy34gnqs4luzb2kfvmmk3q",
    "nonce": 0,
    "value": "100000",
    "gaslimit": 2568147,
    "gasfeecap": "101685",
    "gaspremium": "100631",
    "method": 0,
    "params": ""
  },
  "signature": {
    "type": 2,
    "data": "kzQBZOIN9WPddgINaxpCNJ+NxgdxEQqecB+Id1gOKmj5t7DaZwgfswIrwWSgaj1xDfdGzdT20LTjJrcWwxAoDRdX2iAlTEr5txcmtpdIvPT3sC6RKxjG7kc26AWPiumZ"
  }
}

console.log(fil.getCid(signed));
```

Calling getCid for BLS signed message return `RuntimeError: unreachable`

**Comment by APshenkin** [comment]
Also I found that message signed with BLS pass `verifySignature` check in library, but when sending this message to node I receive `{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"bls signature failed to verify"}}`

**Comment by APshenkin** [comment]
I found that signing message is not correct for BLS signature

I have changed sign method so
```
fn transaction_sign_bls_raw(
    unsigned_message_api: &UnsignedMessageAPI,
    private_key: &PrivateKey,
) -> Result<SignatureBLS, SignerError> {
    let unsigned_message = forest_message::UnsignedMessage::try_from(unsigned_message_api)?;
    let message_cbor = CborBuffer(unsigned_message.to_signing_bytes());

    let sk = bls_signatures::PrivateKey::from_bytes(&private_key.0)?;
    let sig = sk.sign(&message_cbor.0);

    Ok(SignatureBLS::try_from(sig.as_bytes())?)
}
```

and now it's apply to network

**Comment by rllola** [comment]
So you removed the `transaction_serialize` you say it is what is not working ?

**Comment by APshenkin** [comment]
No, I get signing bytes from forest_message::UnsignedMessage directly by `.to_signing_bytes()` method

**Comment by APshenkin** [comment]
Also for `get_cid` issue. Seems it's related with parsing BLS signature.

For now for my internal using I changed `get_cid` method to pass UnsignedMessageAPI to it. (Cid is not related to signature, so I can just pass message without sig)

**Comment by rllola** [comment]
Do you know what version you are using ? I opened an issue for the BLS signature verification on forest side... It has been closed a couple month ago but I am wondering if I have fixed on the lib now...

**Comment by rllola** [comment]
I am able to reproduce the `RuntimeError: unreachable` error. I am fixing this and lets open an other issue for the signing error that you mentioned.

**Comment by APshenkin** [comment]
I didn't changed forest_message version. I tested it in your `dev` branch. (so it's 0.6.0)

Also It would be great to create one more method in WASM - getSigningBytes. In my case I want to construct message, get signing bytes and sign this bytes in other library. I did it in my fork, but maybe this can be useful for somebody else

**Comment by rllola** [comment]
So `transactionSerializeRaw` is the equivalent of the `getSigningBytes` function that you want. Have you tested it ?

Are you signing your BLS transaction using another lib ? If yes can I see it ?

I have added your transaction in the test case. I got a `bls signature verification failed for addr: t3ryp7nacthkhye7dpfzx3fv3btmj5xnegc5v4yqojsaxnhld4jxdqvrsg22qjsuuy34gnqs4luzb2kfvmmk3q` in rust (which should be properly return in WASM so I am fixing that).

**Comment by rllola** [comment]
So it is a similar issue that we had with secp (see https://github.com/Zondax/filecoin-signing-tools/pull/293). They did fix it but I am wondering now if it is also the case for BLS and we missed it.

**Comment by APshenkin** [comment]
> So `transactionSerializeRaw` is the equivalent of the `getSigningBytes` function that you want. Have you tested it ?
> 
> Are you signing your BLS transaction using another lib ? If yes can I see it ?
> 
> I have added your transaction in the test case. I got a `bls signature verification failed for addr: t3ryp7nacthkhye7dpfzx3fv3btmj5xnegc5v4yqojsaxnhld4jxdqvrsg22qjsuuy34gnqs4luzb2kfvmmk3q` in rust (which should be properly return in WASM so I am fixing that).

Yes, my example was from your library. After fix signature was changed.

Here is an example with correct signature
```
{
    "to": "t1kj2fedndezlcawu4nxr6pqisiwz2asgonsy3tny",
    "from": "t3ryp7nacthkhye7dpfzx3fv3btmj5xnegc5v4yqojsaxnhld4jxdqvrsg22qjsuuy34gnqs4luzb2kfvmmk3q",
    "nonce": 0,
    "value": "100000",
    "gaslimit": 2568147,
    "gasfeecap": "101685",
    "gaspremium": "100631",
    "method": 0,
    "params": ""
  },
  "signature": {
    "type": 2,
    "data": "mMQCx8lbADl5CG/gFfiB9kQdH+Wl5MhpYuqBVTx7q9HYvE0MfghQtJzMK6xwqAtiAc+ETa9uBwzbp2tuEx26albpe3N49C8L7WNI19rtOm822z+eQ81eu/DpvC8hsYO4"
  }
}
```

> transactionSerializeRaw
I tried `transactionSerialize` but it wasn't not worked. Will check `transactionSerializeRaw`

**Comment by rllola** [comment]
So the `transactionSerializeRaw` is supposed to return the cbor serialized transaction that's what is expected. I guess `getSigningBytes` would be another kind of function indeed as it will return the CID to be signed.

And you are right the BLS signing function signed the all message and not the CID.

**Comment by rllola** [comment]
This has been fixed. The issue can be closed.
