### ISSUE TITLE
signing tools not working in Safari

### ISSUE THREAD

**Issue by APshenkin** [Zondax/filecoin-signing-tools#352]
u64 and i64 maps to BigUint64Array and BigInt64Array in wasm-bindgen. But these typed arrays are not supported in Safari. I suggest to change them to u32 and i32 if this is possible or pass these params as strings and then parse them to related types in Rust

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array

https://github.com/Zondax/filecoin-signing-tools/blob/master/signer-npm/src/lib.rs#L318

**Comment by emmanuelm41** [comment]
Hi @APshenkin, I just tested the wasm browser example locally on chrome and safari and both of them worked. Could you give me more info to find the error? I may pass by the error without noticing it. I am running it on **Safari Versión 14.1 (16611.1.21.161.6)** 

Screenshot:
![Image](https://user-images.githubusercontent.com/10941036/119351773-3e764300-bc77-11eb-9e79-5362f476687c.png)

**Comment by emmanuelm41** [comment]
I added a new test here #378 and It seems to work great.
