### ISSUE TITLE
`deserializeConstructorParams` errors with certain multisig construction params

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#355]
This is an odd observation, since it seems to have just started happening. Some multisigs (potentially those that were created before mainnet?) error when trying to `deserializeConstructorParams`. Here is both a working and breaking example:

[**Breaking**](https://filfox.info/en/message/bafy2bzaceacyyowgzjc3q3ylrd7zl7wlmhlywt7sjesqfx737vapxcbbdmfhm)
```
constructor_params: "g4FVAddasreLsv6xz4axQS6WkW2AW0DDAQA="
outer message params: "gtgqUwABVQAOZmlsLzEvbXVsdGlzaWdYGoOBVQHXWrK3i7L+sc+GsUEulpFtgFtAwwEA"
```

[**Working**](
https://filfox.info/en/message/bafy2bzacedwaicdhyy4fjdadorm4636t2zbhrlnpsxbzcrkecaaa2dkpahq7a)
```
constructor_params: "hIJVASHGyCRMZSXZ8B8Vz9xt/7c8UepZVQGuJ9ilVJmCabRvCA8mQiWB2bGt7AEaAGA9gBoAAj6w"
params: "gtgqUwABVQAOZmlsLzIvbXVsdGlzaWdYOYSCVQEhxsgkTGUl2fAfFc/cbf+3PFHqWVUBrifYpVSZgmm0bwgPJkIlgdmxrewBGgBgPYAaAAI+sA=="
```

**Comment by rllola** [comment]
I think you are right. The breaking `constructor_params` is from an actor multisig that was in testnet. The parameters are missing the `StartEpoch` value and it is not standard.

**Comment by rllola** [comment]
Unfortunately they changed the actor spec but kept it as V1 `fil/1/multisig` so we can't tell at first glance.

**Comment by rllola** [comment]
No my bad. It was added in v2 and we don't support V1 multisig constructor.

Should I add support for it ?
