### ISSUE TITLE
Missing `lowercase-keys` dependency

### ISSUE THREAD

**Issue by dholms** [Zondax/filecoin-signing-tools#365]
## Problem
`lowercase-keys` is a dependency for the js implementation, however it is not included in `package.json`, so it does not get installed when installing `@zondax/filecoin-signing-tools`. The consumer of the library needs to install it themself.

## Solution
Add `lowercase-keys` to `package.json`

**Comment by emmanuelm41** [comment]
@jleni This issue has been fixed on #369. I think we should close it. The dependency is [here](https://github.com/Zondax/filecoin-signing-tools/blob/d9223687f659ccea95f95c5eb8a772aaff1ffd54/signer-npm/js/package.json#L20)

**Comment by dholms** [comment]
ah yup looks good! Thanks!
