### ISSUE TITLE
Differences between WASM and pure JS lib

### ISSUE THREAD

**Issue by emmanuelm41** [Zondax/filecoin-signing-tools#380]
In WASM lib, we need to pass a buffer to keyRecover. However, the pureJS uses a both string and buffer as input.

WASM lib:
https://github.com/Zondax/filecoin-signing-tools/blob/d0a1a16dfb1ae32c0877b81b08bb96636c4de1c1/examples/wasm_browser/index.js#L31

PureJS lib:
https://github.com/Zondax/filecoin-signing-tools/blob/d0a1a16dfb1ae32c0877b81b08bb96636c4de1c1/signer-npm/js/src/index.js#L44

**Comment by StreamOfMaya** [comment]
Is this related to issue   #205 ?

**Comment by rllola** [comment]
@StreamOfMaya I don't think it is.
