### ISSUE TITLE
Error signing transaction: Error: `Decoding for address failed: non-zero trailing bits at 38`

### ISSUE THREAD

**Issue by EvanXzj** [Zondax/filecoin-signing-tools#383]
```js
const filSigner = require('@zondax/filecoin-signing-tools/nodejs/filecoin_signer_wasm')
const from = 'f1sqjy6vznbl3vq22rnlh5spk2t46uk2uu5lhgqha'
const privateKey = 'xxx'

const unsignedTx = {
        from,
        to: 'f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid',
        nonce: 1,
        value: '40000000000000000',
        gaspremium: '201114',
        gasfeecap: '2083849090',
        gaslimit: 3507254,
        method: 0,
        params: '',
};

filSigner.transactionSign(unsignedTx, privateKey);
```

if to address is `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid`, this demo code will throw error:  `Error signing transaction: Error: `Decoding for address failed: non-zero trailing bits at 38` 

please help!!!

**Comment by EvanXzj** [comment]
![WechatIMG125](https://user-images.githubusercontent.com/18482825/122414934-151cae80-cfba-11eb-9ab0-c46562babe9d.jpeg)

**Comment by rllola** [comment]
Looks like the `to` address is incorrect. Where did you get it ? did you generate it ?

**Comment by EvanXzj** [comment]
@rllola  it is an external address, we don't know how the user got this address.

**Comment by rllola** [comment]
The address ending by `a` is valid and I can sign a transaction for it but the original address doesn't look like a valid one. The user probably enter an incorrect address.

However I don't know if the user meant to send to `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mia`. It could dangerous to change it without warning the user.
