### ISSUE TITLE
multisigCreate broken

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#394]
When trying to use the `createMultisig` function exported from the signing tools (wasm), i get the following error:

```
message execution failed: exit 18, reason: caller type bafkqadlgnfwc6njpmfrwg33vnz2a cannot exec actor type bafkqadtgnfwc6nbpnv2wy5djonuwo (RetCode=18)
```

**Comment by jleni** [comment]
@rllola is this affected by this PR? https://github.com/Zondax/filecoin-signing-tools/pull/395

**Comment by rllola** [comment]
No it shouldn't impact `createMultisig`.

`exit 18` is an error we already had in the past. I don't remember what caused the error exactly. @Schwartz10 I will look at it asap.

**Comment by Schwartz10** [comment]
@rllola I'm naively guessing its something to do with `fil/3/multisig` or something of the sort. I reckon the multisig actor just got changed in an upgrade?

**Comment by rllola** [comment]
Yes the last upgrade included a change for actors. Nothing changed realy just the code CID code actor which is now `fil/5/multisig`.
Did you upgrade to the new version of filecoin-signing-tools for V5 actor ?

**Comment by rllola** [comment]
@Schwartz10 

So using this tool (https://cid.ipfs.io/#bafkqadtgnfwc6nbpnv2wy5djonuwo) you can 'decrypt' what the actor type is.

If you then take the `hex digest` you can then use this tool to decode it to text : https://cryptii.com/pipes/hex-decoder

`66696C2F342F6D756C7469736967` --> `fil/4/multisig` (you might need to upgrade to the version that support V5)

The other type actor is `fil/5/account` and I guess it can only initiate account which are V5 actor too.

Note: The error message is a bit cryptic... Maybe they could improve it and deserialize the actor type.

**Comment by pk-controller** [comment]
I'm still getting this error when I try to create a multisig in GLIF.

estimating gas used: message execution failed: exit 18, reason: caller type bafkqadlgnfwc6njpmfrwg33vnz2a cannot exec actor type bafkqadtgnfwc6nbpnv2wy5djonuwo (RetCode=18)

**Comment by rllola** [comment]
@pk-controller 
The latest version published on npm doesn't include the actor v5 support. You can use the "git+https://github.com/Zondax/
filecoin-signing-tools .git#v0.17.0" temporarily.

We have someone working on publishing the package in npm.
