### ISSUE TITLE
Multisig transactions

### ISSUE THREAD

**Issue by Unded** [Zondax/filecoin-signing-tools#400]
Hi, I am working on signing Multisig transactions and I have difficulties with serialization of parameters in:

https://github.com/Zondax/filecoin-signing-tools/blob/master/signer/src/lib.rs#L557
https://github.com/Zondax/filecoin-signing-tools/blob/master/signer/src/lib.rs#L640
https://github.com/Zondax/filecoin-signing-tools/blob/master/signer/src/lib.rs#L679

1. Do you have plans to add new RPC to the Service for generating JSON multisig transaction with serialized parameters like `sign_transaction` method?
2. Is there any additional information about how to collect Multisig transaction for `propose`, `approve` and `cancel` ?

**Comment by rllola** [comment]
Hi @Unded, 

1. No there is no plan to add new RPC functions to the service.

2. There is no way to collect transaction from multisig. You probably should look at Lotus directly for that.

**Comment by Unded** [comment]
I see, thank you for the answer

**Comment by Unded** [comment]
> No there is no plan to add new RPC functions to the service.
In this way, Is it possible to create Pull Request with new RPCs and new functionality or I have to make fork only?

**Comment by rllola** [comment]
Yeah sure PRs are welcome. I can review them no problem.
