### ISSUE TITLE
transactionSignRaw doesn't work (Emergency Look Please)

### ISSUE THREAD

**Issue by hakimehmordadi** [Zondax/filecoin-signing-tools#405]
I'm working on  offline-signing (raw signing): Steps I did are like below, but I could not send a transaction. Please help. It is emergency. 

```
URL: https://api.node.glif.io
I have a token from lotus deamon

```
const message = {
      "Version": 0,
      "To": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
      "From": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
      "Nonce": 0,
      "Value": "100000",
      "GasPrice": "190464106",
      "GasLimit": 25000,
      "Method": 0,
      "GasPremium": '1',
      "GasFeeCap": '190464106',
      "Params": ""
    };

   1- const cbor = await signer.transactionSerialize(message);
   2- const message = await signer.transactionParse(cbor, false);
   3- let signature =  signer.transactionSignRaw(message, privatekey.toString('hex'));
   4- signature = Buffer.from(signature)
   5- let message_digest1 = getDigest(Buffer.from(cbor, 'hex'));
   6- const bufer =Buffer.from(publickey, 'hex')
   7- const unit8arrayformatofpublickey = new Uint8Array(bufer);
  8- const value = secp256k1.ecdsaVerify(signature.slice(0, -1), message_digest1, unit8arrayformatofpublickey)
  9- const hexSignature = signature.toString('hex');
 10- const signedMessage = {
      Message: message,
      Signature: {
          Data: hexSignature.toString("base64"),
          Type: 1,
      }
    };
11- let response = await axios.post(URL, {
        "jsonrpc": "2.0",
        "method": "Filecoin.MpoolPush",
        "id": 1,
        "params": [signedMessage]
      }, { headers }).catch((e: any) => { console.error(e.message) });

The error is

```
(node:18116) UnhandledPromiseRejectionWarning: Error: No to address provided
    at Object.typeCheck (C:\Users\user\Desktop\server\src\utils.ts:7:28)
    at txCreate (C:\Users\user\Desktop\server\src\server.ts:78:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at main (C:\Users\user\Desktop\server\src\server.ts:124:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Request failed with status code 503
(node:18116) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at txCreate (C:\Users\user\Desktop\server\src\server.ts:120:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at main (C:\Users\user\Desktop\server\src\server.ts:124:3)
(node:18116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

**Comment by hakimehmordadi** [comment]
![paint](https://user-images.githubusercontent.com/31950758/129689531-6ea709a2-39b7-470d-820e-b8d351ca9c7a.png)

**Comment by rllola** [comment]
Try using `transactionSignLotus` instead (see https://github.com/Zondax/filecoin-signing-tools/blob/master/docs/wasm_api.md#transactionsignlotus-support-lotus-schema).

And I don't think your signature is base64 encoded if I am not mistaken lotus only accept base64.

**Comment by hakimehmordadi** [comment]
My requironment is: Sign a message with some parameters offline. For doing
this I need to use transactionSignRaw, I need to serialize  my message.
Something goes bad so I can not send a transaction.

**Comment by rllola** [comment]
`transactionSignLotus` it is an offline function. It just format the response in a proper json so it can be send to a Lotus node directly.

Also your encoding of the signature looks incorrect. You should try using `transactionSignLotus` and compare against you current result. You will see the difference.

**Comment by hakimehmordadi** [comment]
So how can I solve this problem?
How can I encode in the correct format?
Please give me the solution. Suppose there is a message that should be
encoded, which steps and methods should be there?

Thank you

**Comment by rllola** [comment]
It should be encoded in base64 and your private key too.

```javascript
const message = {
"Version": 0,
"To": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
"From": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
"Nonce": 0,
"Value": "100000",
"GasPrice": "190464106",
"GasLimit": 25000,
"Method": 0,
"GasPremium": '1',
"GasFeeCap": '190464106',
"Params": ""
};

const cbor = await signer.transactionSerialize(message);
const message = await signer.transactionParse(cbor, false);
// Your private key should base64 encoded
let signature = signer.transactionSignRaw(message, privatekey.toString('base64'));
signature = Buffer.from(signature)
let message_digest1 = getDigest(Buffer.from(cbor, 'hex'));
const bufer = Buffer.from(publickey, 'hex')
const unit8arrayformatofpublickey = new Uint8Array(bufer);
const value = secp256k1.ecdsaVerify(signature.slice(0, -1), message_digest1, unit8arrayformatofpublickey)
// Your signed message `Data` field should be base64 encode (in your screenshot it is a hex string).
const signedMessage = {
Message: message,
Signature: {
Data: signature.toString("base64"),
Type: 1,
}
};
let response = await axios.post(URL, {
"jsonrpc": "2.0",
"method": "Filecoin.MpoolPush",
"id": 1,
"params": [signedMessage]
}, { headers }).catch((e: any) => { console.error(e.message) });
```
Please note that I haven't tested the code. I let you do it.


You can also try using `transactionSignLotus` it is offline and will fill your requirements. Just so you can compare the result and help you debug.

```javascript
const message = {
"Version": 0,
"To": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
"From": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
"Nonce": 0,
"Value": "100000",
"GasPrice": "190464106",
"GasLimit": 25000,
"Method": 0,
"GasPremium": '1',
"GasFeeCap": '190464106',
"Params": ""
};

// It is an offline function.
let signedMessage = signer.transactionSignLotus(message, privatekey.toString('base64'));
console.log(signedMessage)

let response = await axios.post(URL, {
"jsonrpc": "2.0",
"method": "Filecoin.MpoolPush",
"id": 1,
"params": [signedMessage]
}, { headers }).catch((e: any) => { console.error(e.message) });
```

**Comment by hakimehmordadi** [comment]
It is odd, please take a look at the code below: It is very simple but
didn't create a transaction and transfer money. I don't know what I can do.
I put in a lot of effort and spent much time, but without any result. My
manager is angry with me. Please run this code and let me know what is
wrong. I can not find it. You are familiar with this library. Thank you


"use strict";
import 'reflect-metadata';
const signer = ***@***.***/filecoin-signing-tools');
const FilecoinRPC = ***@***.***/filecoin-signing-tools/utils');
const axios = require('axios');
const bip32 = require('bip32');
import { Message } from ***@***.***/filecoin-message';
const BigNumber = require('bignumber.js');
const fromString = require('uint8arrays/from-string');
const factory = ***@***.***/filecoin-address') ;
const secp256k1 = require('secp256k1');
import { method } from 'lodash';
const BN = require('bn.js');

const URL = "https://api.node.glif.io";
const token =
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.f_asUQSSSHlMgM51IOGLSX0bZwo_s8434jvdRs_4GV0'
;
const headers = { 'Authorization': `Bearer ${token}` }


async function main() {

const message = {
      "From": "f1nfem4vordv7eamgidfgagzo6j6z32nrfoufxx5a",
      "GasLimit": 283763,
      "GasPremium": "56676",
      "GasFeeCap": "65789",
      "Method": 0,
      "Nonce": 9,
      "Params": "",
      "To": "f1susdjal2rogayvfr6m7wypfhawcmuc3ny7v7osi",
      "Value": "100000"
    }

    const MASTER_KEY =
"a71da0d73c04775f8431f8f89d7d68874ae8a2e0461e13e8ed050d90f0479354";
    let MASTER_NODE = bip32.fromBase58(MASTER_KEY);
    const example_key = MASTER_NODE.derivePath("m/44'/461'/0'/0/0");
    const privatekey_base64 = 'px2g1zwEd1+EMfj4nX1oh0roouBGHhPo7QUNkPBHk1Q='
;
    const signed_tx = signer.transactionSign(message, );
    console.log(signed_tx);

    let response = await axios.post(URL, {
        jsonrpc: '2.0',
        method: 'Filecoin.MpoolPush',
        id: 1,
        params: [signed_tx],
      }, { headers }).catch((e: any) => { console.error(e.message) });


    console.log('resoponse', response);

    let cid = await response.data.result;
    console.log('cid', cid);

    response = await axios.post(URL, {
      jsonrpc: '2.0',
      method: 'Filecoin.StateWaitMsg',
      id: 1,
      params: [cid, null],
    }, { headers }).catch((e: any) => { console.error(e.message) });

    console.log('state', response)


}

main()
