### ISSUE TITLE
trouble installing pureJS implementation via npm without bugs

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#424]
Hi, I mentioned this in slack, but figured it was best to create an issue to track it and create a repro repo.

https://github.com/Schwartz10/filecoin-signing-tools-debug

This is a brand new nextjs repository. Simply clone it, `npm i` and then `npm run dev` to start running it and you _should_ get the error:

```
error - Error: Cannot find module 'lowercase-keys'
Require stack:
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/@zondax/filecoin-signing-tools/js/src/index.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/.next/server/pages/index.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/server/require.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/server/load-components.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/build/utils.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/build/output/store.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/build/output/index.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/cli/next-dev.js
- /Users/jonathanschwartz/Documents/glif/signing-tools-debug/node_modules/next/dist/bin/next
```

`filecoin-signing-tools` requires `lowercase-keys`, but that does not automatically get installed by installing `@zondax/filecoin-signing-tools` because the `/js` package.json does not recursively get installed via `npm install` command. Not sure if `yarn` has different behavior for this, since the MetaMask snap does not seem to run into this issue somehow!

**Comment by Anonyma** [comment]
Closing as this was fixed in version 0.18.2
