### ISSUE TITLE
Duplicate symbol '_mod_mul_4w' for architecture x86_64

### ISSUE THREAD

**Issue by daCapricorn** [Zondax/filecoin-signing-tools#426]
The reason is that there are two version of `fff` crates used. Both `fff` contain a ASM file.

```rust
#[link(name = "ff-derive-crypto", kind = "static")]
extern "C" {
    fn mod_mul_4w(a: &[u64; 4], b: &[u64; 4], res: &mut [u64; 4]);
}
```

[https://github.com/filecoin-project/ff/blob/b064b8de977c9fdf0ec90d255b7acc3a7e8dfe8b/src/asm.rs#L7](https://github.com/filecoin-project/ff/blob/b064b8de977c9fdf0ec90d255b7acc3a7e8dfe8b/src/asm.rs#L7)

**Comment by rllola** [comment]
Closing this as I don't have enough information to reproduce it.
