### ISSUE TITLE
Error in ipld-dag-cbor deps

### ISSUE THREAD

**Issue by spylogsster** [Zondax/filecoin-signing-tools#427]
Hello everyone, we got this error today
![image](https://user-images.githubusercontent.com/2965009/148564456-bcdc189d-dac3-4b51-88c4-fc8d9ca2810e.png)

![image](https://user-images.githubusercontent.com/2965009/148564534-09c75e5f-84eb-469c-9511-0017e64686cc.png)

Is this possible to pin all versions to make the library stable?

**Comment by jleni** [comment]
The package `ipld-dag-cbor` has been deprecated and they have not pinned other dependencies either. We are looking at this problem at the moment.

**Comment by jleni** [comment]
This should have been resolved by v0.18.3

**Comment by jleni** [comment]
There is still a case where this lib is being used:

https://github.com/Zondax/filecoin-signing-tools/pull/429/files#diff-793a0a178ed154cad5d52b81e0d4a3f0ec352aeba72c091a65d6cd2b5bc68fb5L32
