### ISSUE TITLE
Alternative for removed "filecoin-service"

### ISSUE THREAD

**Issue by Unded** [Zondax/filecoin-signing-tools#445]
Hi, I have noticed that "filecoin-service" was removed from the repository. (https://github.com/Zondax/filecoin-signing-tools/pull/438)

Furthermore, this project was archived.

Unfortunately, I am  using this project in production for signing transactions offline.

So, is there any alternative for this project which we can use?

**Comment by rllola** [comment]
The underlying lib is still being maintained. You have the possibility to fork the archive project or you can build your own using `filecoin-signing-tools`.

**Comment by jleni** [comment]
@Unded 
Maybe we can maintain it in a different repository?
What are the specific features that you rely on?

**Comment by Unded** [comment]
Maybe yes, now we are using next service's end-points:
* sign_transaction
* gen_create_multisig_tx
* propose_multisig_tx
* approve_multisig_tx
* cancel_multisig_tx

**Comment by rllola** [comment]
Hi @Unded 
After you opened this issue and realizing that the service is being used, we have unarchived the repo and will maintain it:
https://github.com/Zondax/filecoin-service

If you have any issues or requests you can opened a ticket on this new repo.

**Comment by Unded** [comment]
Great news!!! Thank you for the notification
