### ISSUE TITLE
Secp signature verification failed

### ISSUE THREAD

**Issue by carrie143** [Zondax/filecoin-signing-tools#516]
Hi~I got the same error as describe in https://githubhot.com/repo/Zondax/filecoin-signing-tools/issues/422,I get the error message "Secp signature verification failed" when call let hash = signer.getCid(signed_tx_json)

**Comment by rllola** [comment]
Hi @carrie143 
This error has fixed with https://github.com/Zondax/filecoin-signing-tools/pull/444

Could you make sure that you are using the latest version of the library ?
