### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#567]
In https://github.com/Zondax/filecoin-signing-tools/pull/551 we have removed the fuzzing code. When introducing the `remote` serde feature we removed the need for intermediary structure to convert from JSON to CBOR.

Therefore some of the fuzzing code wasn't relevant anymore. However we should not loose the fuzzing feature and would need to see where it is needed now.

:link: [zboto Link](https://app.clickup.com/t/2jug43c)

**Comment by becominginsane** [comment]
I have gone thru the codebase and, whilst I believe fuzzing is good, I doubt it would be very useful in the project.
If we were to fuzz the structures we'd basically be fuzzing serde, and the functionality provided by the main crate is simply a series of operation packages as a simple function, so there are no invariant being held by the library that would benefit from being fuzzed...
We'd simply be fuzzing the parsing being done by thirdy party crates etc. Most operations are fallible and errors are bubbled up, so if we fuzz we'd just be hitting a lot of these cases...
