### ISSUE TITLE
Deprecate `create_multisig`, `proposal_multisig_message`, `create_pymtchan`... etc

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#660]
Deprecate the functions that create messages for special method. Instead the user should serialize the parameters and use to create a valid message.

It will require 2 steps to create a multisig or payment channel actor but offers more visibility on how the the message is build.

:link: [zboto Link](https://app.clickup.com/t/2jug427)

**Comment by Schwartz10** [comment]
Does `serializeParams` already support ConstructorParams? 

> Instead the user should serialize the parameters

Is there an example of this for a multisig actor?

**Comment by rllola** [comment]
I don't have an example for this. It would require to call `serializeParams` twice tho. Once to serialize the constructor parameters and a second time to serialize the cid and serialized parameters for the init actor.
