### ISSUE TITLE
Update `get_status` call to use StateGetReceipt

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#67]
Once `StateGetReceipt` is working we should maybe switch `ChainGetMessage` for this one. The current method return an error if not yet validated and only once we have a result we know it is validated. It is not optimal.

See https://github.com/Zondax/filecoin-rs/pull/63#issuecomment-596542399

**Comment by jleni** [comment]
I think we can close this for now. It is likely that we deprecate the service in this repo.
