### ISSUE TITLE
Remove hardcoded actor code

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-signing-tools#673]
The actor codes CID change too often an required a new release. It would make maintaining project easier if the Actor Code CID is not hardcoded into the lib.

It could not be trivial because we rely on this to know how deserialize parameters. We could however just cbor deserialize generally the parameters and let it to the developer to fill the argument name and type.

:link: [zboto Link](https://app.clickup.com/t/2kbveqx)

**Comment by rllola** [comment]
Now that we have removed the deprecated functions we are now forcing people to check the code cid when creating the parameters. This could be closed but there is still some cleaning to do before.

**Comment by emmanuelm41** [comment]
Closing issue, as the cleaning have been done!
