### ISSUE TITLE
Signer-ffi build doesn't generate files on MacOS

### ISSUE THREAD

**Issue by emmanuelm41** [Zondax/filecoin-signing-tools#681]
I am actually trying to build the lib on MacOS following [this]( https://github.com/Zondax/filecoin-signing-tools/blob/master/.github/workflows/main.yaml#L94-L109) steps. At the end, no `.so` files are generated. I have seen this error on M1 and Intel. 

![image](https://user-images.githubusercontent.com/10941036/181506503-5ea75e3c-b6a5-4169-8248-c09994d903b4.png)

![image](https://user-images.githubusercontent.com/10941036/181506427-f7e82339-11d2-41d5-a824-54d4baee91c4.png)

:link: [zboto Link](https://app.clickup.com/t/2tyncke)

**Comment by emmanuelm41** [comment]
In linux this works
![image](https://user-images.githubusercontent.com/10941036/181510378-dc6e7f10-f78e-4011-b561-6e9d7f2c1300.png)

What I can see is MacOS generates `.dylib` while linux generates `.so`

**Comment by becominginsane** [comment]
That's correct. Linux's dynamic libraries are `.so` files, whilst MacOS's are `.dylib`s
