### ISSUE TITLE
deriveKey into format for importing into lotus CLI

### ISSUE THREAD

**Issue by Schwartz10** [Zondax/filecoin-signing-tools#683]
This is most likely a question and not an issue with the zondax signing tools.

A Glif community member needs to derive a private key from a seed phrase and import that private key into Lotus via the CLI. 

Which of [these getters](https://github.com/glifio/modules/blob/primary/packages/filecoin-wallet-provider/src/%40types/zondax__filecoin-signing-tools/index.d.ts#L8-L13) is the right one to use for importing into Lotus? (It seems like there are a few different supported formats... https://github.com/filecoin-project/lotus/blob/master/cli/wallet.go#L320). 

When the user tried base64 -

```
ERROR: encoding/hex: invalid byte:
```

When the user tried hex:

```
"ERROR: invalid character ‘[redacted]’ looking for beginning of value"
```

Some extra information from the user:

```
"I think the private key is a 160 bit hex number? the one we got is 64 bits only"
```

Thanks for any help!

:link: [zboto Link](https://app.clickup.com/t/2ua4ucy)

**Comment by rllola** [comment]
To import the private key to lotus they should use the `private_base64` getter.

Lotus only support base64 key format
