### ISSUE TITLE
f4 / t4 address support not implemented

### ISSUE THREAD

**Issue by jimpick** [Zondax/filecoin-signing-tools#793]
I was trying to use Filecoin.js to sign a message to a f4* address on the FVM Wallaby testnet, and I was getting an exception with
the message "Unknown protocol indicator byte."

I traced it down the code here:

[[Unknown protoc](https://github.com/Zondax/filecoin-signing-tools/blob/master/signer-npm/js/src/utils.ts#L109)](https://github.com/Zondax/filecoin-signing-tools/blob/945ed77a36ca1f45f075b0e15b1e3c1ae97b5af8/signer-npm/js/src/utils.ts#L109)

There isn't yet a ProtocolIndicator entry for f4 / t4 addresses:

https://github.com/Zondax/filecoin-signing-tools/blob/945ed77a36ca1f45f075b0e15b1e3c1ae97b5af8/signer-npm/js/src/constants.ts

Here is the official FIP for the f4 address class:

https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0048.md

:link: [zboto Link](https://app.clickup.com/t/33duzc0)

**Comment by emmanuelm41** [comment]
Hi @jimpick! Sorry for making you wait for so long. The package is out. Closing the PR.
https://github.com/Zondax/filecoin-signing-tools/releases/tag/v2.0.0
