### ISSUE TITLE
Api to support serializing changeOwnerAddress params

### ISSUE THREAD

**Issue by herryho** [Zondax/filecoin-signing-tools#898]
Hi @rllola , I'm trying to use the library to call changeOwnerAddress method. And I failed to encode the "new owner address" as the input param. Can you please suggest how to format the param for the new  owner address?
Here is a successful changeOwnerAddress transaction from others for your reference:
https://filscan.io/tipset/message-detail?cid=bafy2bzacea7b6fyfvczaz5rfncguuldfkhqhlr2bz3dhq2snc7l3yeuc2k7oq

The command line for calling changeOwnerAddress method is as below:
```
root@ubuntu:~# lotus send --method=23 --from=t3rptkr7r4c2epxlgi5otnn7uurkmys2dwugvsfryqzkapaa3rpizvpc3vnlz74zbpqws5xrjmxtzuq6wqpika --params-json \"t01003\"  t01000 0
```

:link: [zboto Link](https://app.clickup.com/t/8677evw91)

**Comment by emmanuelm41** [comment]
@herryho the send command expects a valid json as input for `--params-json` parameter. Check [this](https://github.com/filecoin-project/lotus/blob/627d6e70a67fe12383eade11e879c259295768ad/cli/services.go#L96-L100) out. The JSON should follow how the parameters struct for that method.
