### ISSUE TITLE
How to generate master_key?

### ISSUE THREAD

**Issue by FatNerdPeng** [Zondax/filecoin-signing-tools#943]
Hello,I have a question:
![image](https://user-images.githubusercontent.com/33616855/229009159-8e9fb3d4-5a33-4394-aef1-ff67eabcd72f.png)
This parameter in this code is generated based on the master_key:
![image](https://user-images.githubusercontent.com/33616855/229009453-a108829e-c9a7-47e7-b644-ac6081897e1b.png)
![image](https://user-images.githubusercontent.com/33616855/229009494-15ab3d45-7c6d-4297-9122-b27b75fc3bea.png)
Is this master_key generated based on the mnemonic above? If so, how was it generated? Are there any libraries or APIs that can be called?
Thanks

:link: [zboto Link](https://app.clickup.com/t/861mkgrv4)

**Comment by emmanuelm41** [comment]
Hey @FatNerdPeng, in the JS side we don't expose a way to generate the master key based on the mnemonic. As you can see here, what you can do is: 
- Generate a mnemonic [🔗](https://github.com/Zondax/filecoin-signing-tools/blob/1407394dfdae7ba0e9fcbf62033f9d35599a5646/signer-npm/js/src/index.ts#L16-L19)
- Derive a key from mnemonic [🔗 ](https://github.com/Zondax/filecoin-signing-tools/blob/1407394dfdae7ba0e9fcbf62033f9d35599a5646/signer-npm/js/src/index.ts#L68-L75)
- Derive a key from a sed [🔗 ](https://github.com/Zondax/filecoin-signing-tools/blob/1407394dfdae7ba0e9fcbf62033f9d35599a5646/signer-npm/js/src/index.ts#L47-L66)


Internally this is how we convert mnemonic to seed [🔗 ](https://github.com/Zondax/filecoin-signing-tools/blob/1407394dfdae7ba0e9fcbf62033f9d35599a5646/signer-npm/js/src/index.ts#L73) and how we derive the master key from seed [🔗 ](https://github.com/Zondax/filecoin-signing-tools/blob/1407394dfdae7ba0e9fcbf62033f9d35599a5646/signer-npm/js/src/index.ts#L52)

---

### ⚠️ Update ⚠️
 Check the new package called [Izari-Filecoin](https://github.com/zondax/izari-filecoin). All JS features has been migrated there, as long as new features. Give it a try.
