### ISSUE TITLE
How to serialize Params in ChangeOnwerAddres transaction

### ISSUE THREAD

**Issue by 247521776** [Zondax/filecoin-signing-tools#987]
```
import signer from '@zondax/filecoin-signing-tools'

console.log(signer.serializeParams("t049626"))
```

:link: [zboto Link](https://app.clickup.com/t/8677zpw93)

**Comment by rllola** [comment]
It is a special case where you only have the address to serialize... (see https://github.com/ChainSafe/fil-actor-states/blob/main/actors/miner/src/v11/types.rs#L72).

We can add support for this.

**Comment by rllola** [comment]
Done!

The parameter should look like this tho : `{"NewOwner": "f17uoq6tp427uzv7fztkbsnn64iwotfrristwpryy"}`
